/**
 * The whole schema as one file, for pasting into the Cloudflare D1 console.
 *
 *   node tools/schema-dump.js            -> werun-schema.sql
 *
 * For the one case the migrations workflow cannot cover: a database that has
 * to be set up by hand, because the API token cannot reach D1 and so the
 * deploy's `wrangler d1 migrations apply` never runs.
 *
 * It reads migrations/ rather than holding its own copy, so it cannot drift,
 * and it writes the d1_migrations rows too — otherwise the first deploy after
 * the token is fixed would try to create every table again and fail.
 *
 * The output is gitignored: generate it when you need it.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DIR = path.join(ROOT, "migrations");
const OUT = path.join(ROOT, "werun-schema.sql");

const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".sql")).sort();
if (!files.length) {
  console.error("no migrations to dump");
  process.exit(1);
}

let out =
  "-- WE RUN — the whole schema, for pasting into the Cloudflare D1 console.\n" +
  "-- Generated by tools/schema-dump.js on " + new Date().toISOString().slice(0, 10) + ".\n" +
  "-- Run it once, against werun-db. Safe to run only on an empty database.\n\n";

for (const f of files) {
  out += "-- ======== " + f + " ========\n" + fs.readFileSync(path.join(DIR, f), "utf8").trim() + "\n\n";
}

out +=
  "-- ======== tell wrangler these are done ========\n" +
  "-- Every deploy runs `wrangler d1 migrations apply`. Without these rows it\n" +
  "-- would try to create all of the above a second time and fail the deploy.\n" +
  "CREATE TABLE IF NOT EXISTS d1_migrations(\n" +
  "  id         INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
  "  name       TEXT UNIQUE,\n" +
  "  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL\n" +
  ");\n" +
  "INSERT OR IGNORE INTO d1_migrations (name) VALUES\n" +
  files.map((f) => "  ('" + f + "')").join(",\n") + ";\n";

fs.writeFileSync(OUT, out);
console.log("wrote " + path.relative(ROOT, OUT) + " — " + files.length + " migrations: " + files.join(", "));
