/**
 * The whole schema as one file, for setting a database up by hand.
 *
 *   node tools/schema-dump.js           -> werun-schema.sql       (commented)
 *   node tools/schema-dump.js --bare    -> werun-schema.bare.sql  (no comments)
 *
 * For the one case the migrations workflow cannot cover: a database that has
 * to be created by hand, because the API token cannot reach D1 and so the
 * deploy's `wrangler d1 migrations apply` never runs.
 *
 * Both read migrations/ rather than holding their own copy, so neither can
 * drift, and both write the d1_migrations rows — otherwise the first deploy
 * after the token is fixed would try to create every table again and fail.
 *
 * Use --bare for Cloudflare's D1 console. Its input collapses newlines on
 * paste, which turns every `-- comment` into one that swallows the rest of
 * the script; with the comments gone there is nothing left to swallow.
 *
 * The output is gitignored: generate it when you need it.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DIR = path.join(ROOT, "migrations");
const bare = process.argv.includes("--bare");
const OUT = path.join(ROOT, bare ? "werun-schema.bare.sql" : "werun-schema.sql");

const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".sql")).sort();
if (!files.length) {
  console.error("no migrations to dump");
  process.exit(1);
}

const LEDGER =
  "CREATE TABLE IF NOT EXISTS d1_migrations(\n" +
  "  id         INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
  "  name       TEXT UNIQUE,\n" +
  "  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL\n" +
  ");\n" +
  "INSERT OR IGNORE INTO d1_migrations (name) VALUES\n" +
  files.map((f) => "  ('" + f + "')").join(",\n") + ";\n";

/**
 * Drop `--` comments and squeeze the whitespace, leaving one statement per
 * line. Quote-aware: a `--` inside a string literal is part of the string,
 * not the start of a comment, and stripping it would silently corrupt data.
 */
function strip(sql) {
  let out = "";
  let inString = false;
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i];
    if (inString) {
      out += c;
      // '' is an escaped quote inside a string, not the end of one.
      if (c === "'") {
        if (sql[i + 1] === "'") out += sql[++i];
        else inString = false;
      }
      continue;
    }
    if (c === "'") {
      inString = true;
      out += c;
      continue;
    }
    if (c === "-" && sql[i + 1] === "-") {
      while (i < sql.length && sql[i] !== "\n") i++;
      out += " ";
      continue;
    }
    out += c;
  }
  return out
    .split(";")
    .map((s) => s.replace(/\s+/g, " ").trim())
    .filter(Boolean)
    .map((s) => s + ";")
    .join("\n");
}

let body = "";
for (const f of files) body += fs.readFileSync(path.join(DIR, f), "utf8").trim() + "\n\n";
body += LEDGER;

let out;
if (bare) {
  out = strip(body) + "\n";
} else {
  out =
    "-- WE RUN — the whole schema, for pasting into a SQL console.\n" +
    "-- Generated by tools/schema-dump.js on " + new Date().toISOString().slice(0, 10) + ".\n" +
    "-- Run it once, against werun-db. Safe to run only on an empty database.\n" +
    "-- For Cloudflare's own D1 console use --bare: that one collapses newlines\n" +
    "-- on paste, which lets a -- comment swallow everything after it.\n\n";
  for (const f of files) {
    out += "-- ======== " + f + " ========\n" + fs.readFileSync(path.join(DIR, f), "utf8").trim() + "\n\n";
  }
  out +=
    "-- ======== tell wrangler these are done ========\n" +
    "-- Every deploy runs `wrangler d1 migrations apply`. Without these rows it\n" +
    "-- would try to create all of the above a second time and fail the deploy.\n" +
    LEDGER;
}

fs.writeFileSync(OUT, out);
const statements = out.split(";").length - 1;
console.log(
  "wrote " + path.relative(ROOT, OUT) + " — " + files.length + " migrations, " +
    statements + " statements" + (bare ? ", no comments" : "")
);
